DROP DATABASE IF EXISTS DBUBIGEOPERU
GO
CREATE DATABASE DBUBIGEOPERU
GO
USE DBUBIGEOPERU
GO

CREATE TABLE DEPARTAMENTO (
IdDepartamento VARCHAR(2) NOT NULL,
Descripcion VARCHAR(45) NOT NULL
);
GO

CREATE TABLE PROVINCIA(
IdProvincia VARCHAR(4) NOT NULL,
Descripcion VARCHAR(45) NOT NULL,
IdDepartamento VARCHAR(2) NOT NULL
);
GO

CREATE TABLE DISTRITO(
IdDistrito VARCHAR(6) NOT NULL,
Descripcion VARCHAR(45) NOT NULL,
IdProvincia VARCHAR(4) NOT NULL,
IdDepartamento VARCHAR(2) NOT NULL
);
GO